### ISSUE TITLE
No highlight with ComplexPhraseQueryParser

### ISSUE THREAD

**Issue by DamienFontaine** [flaxsearch/luwak#136]
I try using ComplexPhraseQueryParser instead of LuceneQueryParser. The doc matches but does not return any highlight.
```
        @Test
	public void complexePhraseQueryParserNormalTest() throws IOException, UpdateException{
		TermFilteredPresearcher presearcher = new TermFilteredPresearcher();
		StandardAnalyzer analyzer = new StandardAnalyzer();
		String field = "text";
		MonitorQuery mq1 = new MonitorQuery("1", "\"Miss Taylor\"");
		String documentId = "1";
		String content = "Her name is Miss Taylor. Miss Taylor.";
		
		MonitorQueryParser parser = new MonitorQueryParser() {
			@Override
			public Query parse(String queryString, Map<String, String> metadata) throws Exception {
				return new ComplexPhraseQueryParser(field, analyzer).parse(queryString);
			}
		};
		
		try (Monitor monitor = new Monitor(parser, presearcher)) {
			monitor.update(mq1);
			InputDocument doc = InputDocument.builder(documentId).addField(field, content, analyzer).build();

			Matches<HighlightsMatch> matches = monitor.match(doc, HighlightingMatcher.FACTORY);
			for (DocumentMatches<HighlightsMatch> docMatches : matches) {
				Assert.assertTrue("Must match 1 document but " + docMatches.getMatches().size(), docMatches.getMatches().size() == 1);
				for (HighlightsMatch match : docMatches) {
					Collection<Hit> hits = match.getHits("text");
					Assert.assertTrue("Must return 4 hits but " + hits.size(), hits.size() == 4);
				}
			}
		}
	}
```

Thanks.

**Comment by mjustice3** [comment]
I've run into similar issues although not exactly this one. I think if you change your final for loop to:

```
            for (HighlightsMatch match : docMatches) {
                if (match.error != null) {
                    match.error.printStackTrace();
                } else {
                    Collection<Hit> hits = match.getHits("text");
                    Assert.assertTrue("Must return 4 hits but " + hits.size(), hits.size() == 4);
                }
            }
```

you'll see that the SpanRewriter doesn't know how to rewrite a ComplexPhraseQuery. I have some custom queries that SpanRewriter doesn't know about and the solution was to extend SpanRewriter and override the rewrite() method so that the additional queries were handled. Having said that, the ComplexPhraseQuery seems like it might be an especially tough case.

**Comment by DamienFontaine** [comment]
Yes, you are right. This error is returned by luwak:
```
uk.co.flax.luwak.util.RewriteException: Don't know how to rewrite class org.apache.lucene.queryparser.complexPhrase.ComplexPhraseQueryParser$ComplexPhraseQuery
	at uk.co.flax.luwak.util.SpanRewriter.rewriteUnknown(SpanRewriter.java:128)
	at uk.co.flax.luwak.util.SpanRewriter.rewrite(SpanRewriter.java:63)
	at uk.co.flax.luwak.util.SpanRewriter.rewrite(SpanRewriter.java:44)
	at uk.co.flax.luwak.matchers.HighlightingMatcher.doMatch(HighlightingMatcher.java:143)
	at uk.co.flax.luwak.matchers.HighlightingMatcher.doMatchQuery(HighlightingMatcher.java:59)
	at uk.co.flax.luwak.CandidateMatcher.matchQuery(CandidateMatcher.java:68)
	at uk.co.flax.luwak.Monitor$StandardQueryCollector.matchQuery(Monitor.java:562)
	at uk.co.flax.luwak.QueryIndex$MonitorQueryCollector.collect(QueryIndex.java:247)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:221)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:172)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:669)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:473)
	at uk.co.flax.luwak.QueryIndex.search(QueryIndex.java:112)
	at uk.co.flax.luwak.Monitor.match(Monitor.java:481)
	at uk.co.flax.luwak.Monitor.match(Monitor.java:448)
	at uk.co.flax.luwak.Monitor.match(Monitor.java:462)
	at com.viasema.gate.luwak.service.LuwakServiceTest.testComplexePhraseQueryParser(LuwakServiceTest.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by romseygeek** [comment]
Yes, this is in general a problem when using the HighlightingMatcher with non-standard queries.  One way round it might be to change the matcher to rewrite the query before it's used, as things normally get rewritten to one of a small set of core queries - ComplexPhraseQuery rewrites itself to booleans or phrase queries, which will be understood.

**Comment by romseygeek** [comment]
Rewriting the query before it gets passed to SpanRewriter doesn't work, because MTQs get rewritten to private classes.  Instead, if the SpanRewriter doesn't understand the query, it should try as a last resort to rewrite it against an IndexSearcher, and then convert that rewritten query to Spans.  Most weird query parser queries (including ComplexPhraseQuery) will rewrite themselves to a core query that the SpanRewriter will know how to deal with.  @DamienFontaine Can you try out the PR and see if it fixes your issue?  

@mjustice3 , you might find that this helps our your custom query setup as well.

**Comment by DamienFontaine** [comment]
@romseygeek I tried with several expressions (ordered, unordered, fuzzy, wildcard). It works !
Thanks.

**Comment by romseygeek** [comment]
Thanks for testing!
